Update ci.yml, cd.yml et dast.yml...

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -30,20 +30,20 @@ jobs:
                     EVENT="${{ github.event_name }}"
 
                     if [ "$EVENT" = "pull_request" ]; then
-                    BRANCH="${{ github.base_ref }}"
+                        BRANCH="${{ github.base_ref }}"
                     else
-                    BRANCH="${{ github.ref_name }}"
+                        BRANCH="${{ github.ref_name }}"
                     fi
 
                     echo "Event: $EVENT"
                     echo "Target branch: $BRANCH"
 
                     if [ "$BRANCH" = "main" ]; then
-                    echo "✅ Allowed branch '$BRANCH' to trigger deploy."
-                    exit 0
+                        echo "✅ Allowed branch '$BRANCH' to trigger deploy."
+                        exit 0
                     else
-                    echo "::error ::Branch '$BRANCH' is not allowed to trigger deploy."
-                    exit 1
+                        echo "::error ::Branch '$BRANCH' is not allowed to trigger deploy."
+                        exit 1
                     fi
 
     check-security-scans:
diff --git a/.github/workflows/dast.yml b/.github/workflows/dast.yml
--- a/.github/workflows/dast.yml
+++ b/.github/workflows/dast.yml
@@ -40,6 +40,9 @@ jobs:
     dynamic-api-scan:
         needs: check-ci-status
         runs-on: ubuntu-latest
+        env:
+            API_URL: http://localhost:8080
+            DOCKER_API_URL: http://api:80
         steps:
             -
                 name: Checkout Code
@@ -59,10 +62,16 @@ jobs:
             #         -config replacer.full_list(1).replacement=Bearer ${{ secrets.BASIC_AUTH }}
             #         EOF
 
+            - 
+                name: Generate SECRET_KEY
+                id: generate_secret
+                run: |
+                    echo "SECRET_KEY=$(openssl rand -hex 32)" >> $GITHUB_OUTPUT
+
             -
                 name: Build Docker Image
                 run: |
-                    docker build -f ./Dockerfile -t dev-sec-ops/api-rest-crud .
+                    docker build -f ./Dockerfile.zap -t dev-sec-ops/api-rest-crud .
 
             - 
                 name: Create Docker Network
@@ -71,7 +80,33 @@ jobs:
             - 
                 name: Run Application Container
                 run: |
-                    docker run -d --name api --network zap-net -p 8080:80 dev-sec-ops/api-rest-crud
+                    docker run -d --name api --network zap-net -p 8080:80 \
+                        -e SQLALCHEMY_DATABASE_URL="sqlite:////usr/src/app/test.db" \
+                        -e SECRET_KEY="${{ steps.generate_secret.outputs.SECRET_KEY }}" \
+                        -e API_URL=$DOCKER_API_URL \
+                        dev-sec-ops/api-rest-crud
+
+            - 
+                name: Wait for API to be ready
+                run: |
+                    echo "Waiting for API to be ready..."
+                    for i in {1..30}; do
+                        if curl -f $API_URL; then
+                        echo "API is up!"
+                        exit 0
+                        fi
+                        sleep 2
+                    done
+                    echo "API failed to start in time"
+                    docker logs api
+                    exit 1
+
+            - 
+                name: Run tests inside Docker and extract token
+                id: auth
+                run: |
+                    TOKEN=$(docker exec api pytest tests/auth_flow.py -s | grep "ADMIN_TOKEN=" | cut -d= -f2)
+                    echo "token=$TOKEN" >> $GITHUB_OUTPUT
             
             - 
                 name: Pull ZAP OWASP Image
@@ -80,7 +115,7 @@ jobs:
             - 
                 name: Run ZAP API Passive Scan
                 run: |
-                    sudo docker run --rm --user root --network zap-net -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-weekly zap-baseline.py -t http://api:80/openapi.json -g zap_passive_scan_$(date -u +'%Y%m%d').conf -r zap_passive_scan_report_$(date -u +'%Y%m%d').html
+                    sudo docker run --rm --user root --network zap-net -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-weekly zap-baseline.py -t $DOCKER_API_URL/openapi.json -g zap_passive_scan_$(date -u +'%Y%m%d').conf -r zap_passive_scan_report_$(date -u +'%Y%m%d').html
                 continue-on-error: true
 
             # - 
@@ -93,7 +128,7 @@ jobs:
                 name: Run ZAP Basic Full Scan
                 uses: zaproxy/action-full-scan@v0.13.0
                 with:
-                    target: http://api:80
+                    target: $DOCKER_API_URL
 
             -
                 name: Run ZAP Advanced API Scan
@@ -102,14 +137,14 @@ jobs:
                     token: ${{ secrets.GITHUB_TOKEN }}
                     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
                     format: openapi
-                    target: http://api:80
+                    target: $DOCKER_API_URL
                     cmd_options: '-a'
                     allow_issue_writing: true
                     issue_title: ZAP Advanced API Scan ${{ github.sha }}
                     artifact_name: zap-api-scan-report
                 env:
                     ZAP_AUTH_HEADER: Authorization
-                    ZAP_AUTH_HEADER_VALUE: Bearer ...
+                    ZAP_AUTH_HEADER_VALUE: Bearer ${{ steps.auth.outputs.token }}
             
             -
                 name: Run ZAP Advanced Full Scan
